# web-xxe-ssrf — Portal de facturación XXE + SSRF a metadata service
# Lanzar: TEAM_ID=team_02 TEAM_N=2 FLAG="HL4{...}" CHAL_NET=ctf_team_02 docker compose up -d --build
networks:
  team_net:
    external: true
    name: ${CHAL_NET:-ctf_local}
  internal_net:
    driver: bridge
    internal: true

services:
  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    image: web-xxe-ssrf-webapp
    environment:
      FLAG: "${FLAG:-HL4{EJEMPLO_LOCAL}}"
      TEAM_ID: "${TEAM_ID:-team_local}"
      CHALLENGE_ID: "web-xxe-ssrf"
    networks:
      team_net:
        ipv4_address: 172.30.${TEAM_N:-99}.12
      internal_net:
    restart: unless-stopped

  metadata-service:
    build:
      context: .
      dockerfile: metadata-service/Dockerfile
    image: web-xxe-ssrf-metadata
    environment:
      FLAG: "${FLAG:-HL4{EJEMPLO_LOCAL}}"
    networks:
      internal_net:
    restart: unless-stopped
