# pwn-aarch64-rop — AArch64 ROP chain (emulado con qemu-user-static)
# TEAM_ID=team_05 TEAM_N=5 FLAG="HL4{...}" CHAL_NET=ctf_team_05 docker compose up -d --build
networks:
  team_net:
    external: true
    name: ${CHAL_NET:-ctf_local}

services:
  app:
    build: .
    image: pwn-aarch64-rop-app
    environment:
      FLAG: "${FLAG:-HL4{f4ke_4arch64_r0p}}"
      TEAM_ID: "${TEAM_ID:-team_local}"
      CHALLENGE_ID: "pwn-aarch64-rop"
    networks:
      team_net:
        ipv4_address: 172.30.${TEAM_N:-99}.30
    restart: unless-stopped
