# pwn-srop-chain — SROP, binario minimalista sin libc
# TEAM_ID=team_04 TEAM_N=4 FLAG="HL4{...}" CHAL_NET=ctf_team_04 docker compose up -d --build
networks:
  team_net:
    external: true
    name: ${CHAL_NET:-ctf_local}

services:
  app:
    build: .
    image: pwn-srop-chain-app
    environment:
      FLAG: "${FLAG:-HL4{f4ke_sr0p_fl4g}}"
      TEAM_ID: "${TEAM_ID:-team_local}"
      CHALLENGE_ID: "pwn-srop-chain"
    networks:
      team_net:
        ipv4_address: 172.30.${TEAM_N:-99}.30
    restart: unless-stopped
